### ISSUE TITLE
Render CR line endings

### ISSUE THREAD

**Issue by SarenCurrie** [atom/superstring#33]
Since Atom 1.19, files with CR only line endings are no longer rendered correctly. While mostly just for legacy use-cases, there are still some formats that require CR only endings (for example the [HL7v2 standard](https://blog.interfaceware.com/hl7-delimiter-characters/), widely used in health IT).

It looks as if the following code is responsible for this issue.

```cpp
const uint16_t *TextBuffer::line_ending_for_row(uint32_t row) {
  if (row > extent().row) return nullptr;

  static uint16_t LF[] = {'\n', 0};
  static uint16_t CRLF[] = {'\r', '\n', 0};
  static uint16_t NONE[] = {0};

  const uint16_t *result = NONE;
  top_layer->for_each_chunk_in_range(
    Point(row, UINT32_MAX),
    Point(row + 1, 0),
    [&result](TextSlice slice) {
      auto begin = slice.begin();
      if (begin == slice.end()) return false;
      result = (*begin == '\r') ? CRLF : LF;
      return true;
    }, true);
  return result;
}
```

**Comment by maxbrunsfeld** [comment]
We have actually intentionally dropped support for CR line endings. It's not just this method; there are several places in the codebase that assume that lines end with a `\n` character. Treating CRs as line endings adds significant complexity, and caused Atom to disagree with many common tools like `vim`, `wc` and `grep` about what constitutes a 'line'.

I'm not strongly opposed to adding support for this again at some point, maybe behind some config setting, but it is not a simple change, and when we rewrote the text buffer in Atom 1.19, it didn't seem to make sense from a complexity/benefit perspective.
