### ISSUE TITLE
Fuzzy matching improvements

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom/superstring#36]
Here's a couple of minor grievances I've come up with regarding our new fuzzy matching. Feel free to add others. I'm not sure how urgent these things are. But if we can all agree on them, they're probably worth doing before the autocomplete changes ship, because they should be fairly minor code changes.

1. [x] The casing of each letter in the query should be taken into account during sorting. For example, when I type `pac`, the word `package` should be provided as a suggestion *before* the word `Package`, because if I typed a lowercase `p`, I'm more likely trying to type `package` than `Package`.

2. [x] All else being equal, shorter matches should be suggested *before* longer ones. For example, if I type `pac`, the word `package` should be provided *before* the words `packageDependencies` or `packageDirPaths`, because if I want one of those longer words, I can bring it to the top of the list by continuing to type more characters.

/cc @nathansobo @leroix

**Comment by nathansobo** [comment]
These seem reasonable to me. How would we articulate these in terms of rewards and penalties. I guess there could be a reward for matching cases and a penalty for each trailing letter to make longer words score worse. The trailing letter penalty seems very related to the penalty for mismatched letters... maybe it's just an extension of that behavior.

**Comment by maxbrunsfeld** [comment]
> The trailing letter penalty seems very related to the penalty for mismatched letters... maybe it's just an extension of that behavior.

Yeah, maybe it's as simple as penalizing all of the mismatched letters in a word, rather than just those that occur before the last letter of the query is matched.

**Comment by leroix** [comment]
I definitely agree that these behaviors should be changed.

**Comment by nathansobo** [comment]
@leroix Would you be willing to take it on? I can help with any workflow issues you may have around testing the native module.

**Comment by leroix** [comment]
I think https://github.com/atom/superstring/pull/37 may have had the added bonus of fixing item#1 in this issue, but I'm trying to fully verify.

**Comment by leroix** [comment]
It looks like I need to use the same sorting scheme when sorting the final merged matches from all the buffers in ac+.

**Comment by leroix** [comment]
With #38 and https://github.com/atom/autocomplete-plus/pull/902 merged, these changes will show up in Atom shortly. I'm going to go ahead and close.
