### ISSUE TITLE
Saving a document with emoji in ISO-8859-1 causes infinite looping

### ISSUE THREAD

**Issue by Ingramz** [atom/superstring#47]
To reproduce:
1) Create a new document or open existing in Atom
2) Select ISO 8859-1 as character encoding for the document
3) Paste in an emoji, like this one here: 🐈 
4) Try saving
5) Notice high CPU usage by Atom, the save not completing and the file at the destination being empty.

cc @maxbrunsfeld @50Wliu

**Comment by maxbrunsfeld** [comment]
Thanks so much for the report @Ingramz. Fixing now.

**Comment by maxbrunsfeld** [comment]
The fix will go out when we release 1.23 and 1.24 Beta next week.
