### ISSUE TITLE
npm install fails with Node 12

### ISSUE THREAD

**Issue by akurtakov** [atom/superstring#75]
### Description

npm install with Node 12 fails

### Steps to Reproduce

1. clone the repo
2. make sure you are using Node 12.x
3. npm install

**Expected behavior:**

Installs just fine

**Actual behavior:**

../src/bindings/marker-index-wrapper.cc:350:43: error: no matching function for call to ‘v8::Integer::NumberValue()’
  350 |     max_count = js_max_count->NumberValue();
      |                                           ^
Is the last error but there are previous too.

**Reproduces how often:**

Always

### Versions

Current master

**Comment by Arcanemagus** [comment]
Work is currently underway on this in https://github.com/atom/superstring/pull/72.

**Comment by akurtakov** [comment]
So next thing is - when is release with this patch planned so it can be freely used on Node 12?

**Comment by akurtakov** [comment]
Please cut out new release.

**Comment by smackesey** [comment]
Is this library supposed to be compatible with newer Node versions? I am trying to do some contributions for node-tree-sitter but its dependency makes my `npm install` fail. I'm on Node 14.

**Comment by DeeDeeG** [comment]
This should be fixed now. CI is testing with 12.14.1 and passing (if you disregard CircleCI, which isn't running).

**Comment by aminya** [comment]
This should be closed. It is already fixed.
